### ISSUE TITLE
Create a 0x Exchange imitator smart contract

### ISSUE THREAD

**Issue by mpsido** [mpsido/dexExchange#1]
Create a smart contract having the same API as this one: https://etherscan.io/address/0x080bf510fcbf18b91105470639e9561022937712#code

The client code calling this smart contract must be the same as the code able to call the original smart contract.

A first version of this contract just forwards the function call to the original contract.

**Comment by arseneeth** [comment]
Proxy contract could be found here: https://github.com/mpsido/dexExchange/blob/master/contracts/proxy.sol 

it does not implement any functions yet, but could act as an interface to the original contract
